spring.application.name=sa-backend

spring.datasource.url=jdbc:mariadb://localhost:3307/SA
spring.datasource.username=${USERNAME}
spring.datasource.password=${PASSWORD}
#spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

server.servlet.context-path=/api

springdoc.swagger-ui.path=/v1/swagger-ui.html

spring.ai.google.genai.chat.options.model=gemini-2.5-flash-lite
spring.ai.model.chat=google-genai
spring.ai.google.genai.api-key=${API_KEY} 

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${EMAIL_USERNAME}
spring.mail.password=${EMAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.prompt.sentiment="Agis comme un expert en analyse de données.\nAnalyse le sentiment du texte suivant et réponds exclusivement par un seul mot : 'POSITIF', 'NEGATIF' ou 'NEUTRE'.\nNe donne aucune explication, ni introduction, ni ponctuation supplémentaire.\nTexte à analyser : [%s]"

app.prompt.email="Tu es un assistant qui génère des emails structurés pour une application Java.\n\nGénère un email qui respecte exactement la structure de la classe suivante :\n\npublic class Email {\nprivate String from;\nprivate String to;\nprivate String subject;\nprivate String body;\n}\n\nInstructions :\n\n* Retourne la réponse au format JSON.\n* Ne fait aucun commentaire, aucune explication, n'ajoute rien.\n* Les champs doivent correspondre exactement aux attributs de la classe.\n* \"from\" et \"to\" doivent être des adresses email valides.\n* \"subject\" doit être court et professionnel.\n* \"body\" doit contenir le texte complet de l?email.\n\nContexte de l?email :\n[%s]\n\nFormat de réponse attendu :\n\n{\n\"from\": \"\",\n\"to\": \"\",\n\"subject\": \"\",\n\"body\": \"\"\n}"

app.email=${APP_EMAIL}